openapi: 3.0.3
info:
  title: Authors Management
  description: API for authors management
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /authors:
    get:
      summary: Retrieve a list of authors
      parameters:
        - name: authorName
          in: query
          required: false
          description: Filter by author name
          schema:
            type: string
      responses:
        '200':
          description: A list of authors
    post:
      summary: Add a new author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                sex:
                  type: string
                  enum: [M, F]
      responses:
        '201':
          description: Author created