openapi: 3.0.3
info:
  title: Book Management
  description: API for book management
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /books:
    get:
      summary: Get a list of books
      parameters:
        - name: bookName
          in: query
          required: false
          description: Filter by book name
          schema:
            type: string
        - name: releaseDate
          in: query
          required: false
          description: Filter by release date range
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of books
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bookName:
                  type: string
                author:
                  type: string
                pageNumbers:
                  type: integer
                topic:
                  type: string
                  enum: [ROMANCE, COMEDY, OTHER]
                releaseDate:
                  type: string
                  format: date
      responses:
        '201':
          description: Book created