openapi: 3.0.3
info:
  title: Book Management
  description: API for book management
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /books:
    get:
      summary: Get a list of books
      parameters:
        - name: bookName
          in: query
          required: false
          description: Filter by book name
          schema:
            type: string
        - name: releaseDate
          in: query
          required: false
          description: Filter by release date range
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of books
  
